export default `
0: (?:(?:(?:b(?:(?:a(?:a(?:bba|bab)|b(?:a(?:aa|b(?:b|a))|b(?:a(?:b|a)|bb)))|b(?:(?:(?:(?:b|a)(?:b|a))a|(?:ab|ba)b)a|(?:(?:a(?:b|a)|bb)a|abb)b))a|(?:a(?:a(?:aba|(?:ab|aa)b)|b(?:aba|(?:ab|ba)b))|b(?:aaab|(?:b(?:aa|bb)|a(?:aa|ba))a))b)|a(?:b(?:b(?:(?:b(?:aa|b(?:b|a))|a(?:ab|ba))b|(?:aba|b(?:a(?:b|a)|ba))a)|a(?:(?:b(?:aa|bb)|a(?:aa|ba))b|(?:(?:b(?:b|a)|ab)b|baa)a))|a(?:(?:(?:a(?:b(?:b|a)|ab)|b(?:bb|ab))b|(?:(?:a(?:b|a)|bb)b|(?:aa|ba)a)a)a|(?:b(?:a(?:b(?:b|a)|ab)|b(?:bb|ab))|a(?:(?:(?:b|a)(?:b|a))a|(?:ab|ba)b))b)))b|(?:(?:(?:(?:(?:(?:b(?:b|a)|ab)b|(?:bb|ab)a)a|(?:(?:aa|b(?:b|a))b|(?:(?:b|a)(?:b|a))a)b)a|(?:(?:bab|baa)a|(?:a(?:a(?:b|a)|ba)|b(?:b(?:b|a)|ab))b)b)a|(?:b(?:b(?:baa|(?:bb|ab)b)|a(?:(?:aa|ba)b|(?:b(?:b|a)|ab)a))|a(?:a(?:(?:aa|b(?:b|a))b|(?:bb|ab)a)|b(?:aaa|bba)))b)a|(?:b(?:a(?:(?:(?:bb|ab)b)b|(?:(?:ab|ba)a|bab)a)|b(?:b(?:(?:ab|aa)a|(?:aa|bb)b)|a(?:(?:aa|ba)b|(?:b(?:b|a)|ab)a)))|a(?:b(?:b(?:b(?:bb|ab)|aaa)|a(?:aab|(?:ab|aa)a))|a(?:b(?:bab|aba)|a(?:(?:aa|ba)a|(?:ab|ba)b))))b)a))(?:(?:(?:b(?:(?:a(?:a(?:bba|bab)|b(?:a(?:aa|b(?:b|a))|b(?:a(?:b|a)|bb)))|b(?:(?:(?:(?:b|a)(?:b|a))a|(?:ab|ba)b)a|(?:(?:a(?:b|a)|bb)a|abb)b))a|(?:a(?:a(?:aba|(?:ab|aa)b)|b(?:aba|(?:ab|ba)b))|b(?:aaab|(?:b(?:aa|bb)|a(?:aa|ba))a))b)|a(?:b(?:b(?:(?:b(?:aa|b(?:b|a))|a(?:ab|ba))b|(?:aba|b(?:a(?:b|a)|ba))a)|a(?:(?:b(?:aa|bb)|a(?:aa|ba))b|(?:(?:b(?:b|a)|ab)b|baa)a))|a(?:(?:(?:a(?:b(?:b|a)|ab)|b(?:bb|ab))b|(?:(?:a(?:b|a)|bb)b|(?:aa|ba)a)a)a|(?:b(?:a(?:b(?:b|a)|ab)|b(?:bb|ab))|a(?:(?:(?:b|a)(?:b|a))a|(?:ab|ba)b))b)))b|(?:(?:(?:(?:(?:(?:b(?:b|a)|ab)b|(?:bb|ab)a)a|(?:(?:aa|b(?:b|a))b|(?:(?:b|a)(?:b|a))a)b)a|(?:(?:bab|baa)a|(?:a(?:a(?:b|a)|ba)|b(?:b(?:b|a)|ab))b)b)a|(?:b(?:b(?:baa|(?:bb|ab)b)|a(?:(?:aa|ba)b|(?:b(?:b|a)|ab)a))|a(?:a(?:(?:aa|b(?:b|a))b|(?:bb|ab)a)|b(?:aaa|bba)))b)a|(?:b(?:a(?:(?:(?:bb|ab)b)b|(?:(?:ab|ba)a|bab)a)|b(?:b(?:(?:ab|aa)a|(?:aa|bb)b)|a(?:(?:aa|ba)b|(?:b(?:b|a)|ab)a)))|a(?:b(?:b(?:b(?:bb|ab)|aaa)|a(?:aab|(?:ab|aa)a))|a(?:b(?:bab|aba)|a(?:(?:aa|ba)a|(?:ab|ba)b))))b)a)(?:(?:a(?:a(?:b(?:(?:b(?:aa|ba)|aaa)b|(?:b(?:ab|aa)|a(?:ab|ba))a)|a(?:(?:aab|bbb)b|(?:aab|baa)a))|b(?:(?:(?:b(?:a(?:b|a)|bb)|aaa)b|(?:(?:ab|aa)b|(?:aa|ba)a)a)a|(?:a(?:(?:a(?:b|a)|ba)b|bba)|b(?:bab|a(?:aa|bb)))b))|b(?:a(?:b(?:a(?:aba|(?:ab|aa)b)|b(?:b(?:a(?:b|a)|bb)|aab))|a(?:(?:aaa|b(?:(?:b|a)(?:b|a)))b|(?:(?:a(?:b|a)|ba)a|(?:a(?:b|a)|bb)b)a))|b(?:(?:(?:b(?:a(?:b|a)|bb)|aab)b|(?:aab|bbb)a)a|(?:a(?:(?:b(?:b|a)|ab)b|(?:bb|ab)a)|b(?:(?:ab|ba)a|(?:(?:b|a)(?:b|a))b))b)))b|(?:a(?:b(?:a(?:(?:aba|(?:b(?:b|a)|ab)b)a|(?:abb|b(?:(?:b|a)(?:b|a)))b)|b(?:a(?:(?:b(?:b|a)|ab)(?:b|a))|b(?:(?:aa|b(?:b|a))a|(?:aa|ba)b)))|a(?:(?:b(?:aab|(?:ab|aa)a)|a(?:(?:ab|aa)a|(?:aa|bb)b))a|(?:(?:b(?:aa|b(?:b|a))|a(?:bb|ab))a|(?:a(?:aa|bb)|b(?:a(?:b|a)|bb))b)b))|b(?:a(?:(?:(?:(?:b|a)(?:a(?:b|a)|ba))b|(?:(?:a(?:b|a)|bb)b|(?:aa|bb)a)a)b|(?:(?:aaa|abb)a|(?:aaa|(?:bb|ab)b)b)a)|b(?:a(?:a(?:b(?:aa|b(?:b|a))|a(?:ab|ba))|b(?:aba|bbb))|b(?:(?:aba|(?:ab|ba)b)a|(?:b(?:a(?:b|a)|ba)|abb)b))))a))


aaaabbaaaaababbaabbbbbbbabbbbaabbabaabbbbbbbaaba
ababaaabbbabababbabbbbba
bbbbaaaaabbbababaaabbbaa
bbbbbaaaabbbababbaaaabab
aaabaababbabaabaaabababaabaaaaabbbbabbba
bbaaabababbaabbbbabaaababababaaaabbbaaba
bbbaabbabaabaabaababaaaaabaaabaabaabbbabbaababbb
aaaaaabbabbaabbbbbbbaaaaaaaaabab
bbaaabbbbaababaabbbbbbaabbbbababbabbabaaaabaababbaaaaabbaabaaaba
ababbbbbabbaabbbbbbbbaab
aabbabaaaaabbaabaaaaaabb
aaabaabaaababbabaaabbaba
bbbaaaabbbbbaaabbababaabaaaaabba
aaaabbbbaaabaabaaaaaaaabbaabbaaababbbbbb
bbbbbbaabbaaababababbaaabbabbbaabaaaaaaa
aaabbaaaaabababaaababbbbabbbbabbbabaaaabbbbaabbb
baabbbbbaabbbabaabbaaabbbaaaabaababaabbaabbabaaa
abbaaababaaabbbaaabbbababbaabbbb
bbbaaababbbbaaabbaabbbaaaaaabababbaabaaaabbaaaababbabbaa
bbaaaaabbbabbabbbbabbbaa
baabababbbaaababbabababbabaaabab
babbababbbaaababbbaaaaaabababbbbabaabbaababbbbaabbbaabab
bababbbbbbaaaaaabaabbbbb
aabaaaabbabababbabaaaabaaabbaaaabbabbbbbbbbbabaaababbabb
baabbaabaababbabbabbbaab
abaaabaaabbbabababbababbbaaaaaab
babbaaabaabababaabaabababaaababa
bbbaaaaaaaabbbababaaabab
aaababaaaabaabbbaabaaaabbbababbabababbabaaabbaabbbaabbababbaabab
abbbaabbbabababbbabaabaabbaabbbbabaabbbb
aaaaaaabbaabaabaaabbaaab
aabbabbabbabaabbabaababaaaaaabaa
aaabbaabbabaabaababbbbaa
baabaababbabbaababbabaabbbabbaabaaabbabbabbaaabb
babbbbabbaababaababbbbabbbbaabab
bbaaaaaaabbbbbaabbbbbaabbaaaabbb
aabbbbbbaabbabbabbbbaaaabbbaaaaaabbbaabaabaabaaa
aaabbabbbaaababbaaabaaaabbbaaaaaabbbbbabbababbba
ababbaaabbbabaabbabbbbabbababababababaabaabaaabb
babaaabababaaaaaabaaabbabbaaaababaababbb
bbbabaabaaaaaaabaaabbaaabaababbb
abbaaaaaabbaaabababababababaaaaabaabbbbbabbabbba
abbbaabbbaabaabaaaabbbabaabaabba
aababbaabbaaaaaaaabaabbbbbababaaabababaa
aaabbabbbabaaababaabaaab
bbaaaabbaaabbabbbbbabaababbbbabaabbabbba
bababaaabbaaaaaabaaaabba
baaabaaabaaabbbbbaaaaaaa
bbbaaabaababaabbbbbaabbaaaaaaaabaabbabab
abaababaaabbaaaaaabaabaaabbbabba
aabbbbbbbaaabbbbaaabaabbbbbaaabaabbaaabaabbbababbabbabba
bbaababaaabbbbabbbbaaabbbbbbbbbaabbbabbbaaaaabaa
aabababbaaabaaaaaaaaabab
babaabbbabaaaaaaababbabaababbbbaaaabbaaabbbaabaa
aabaaaabbbaaabbaaabababbbbbbbabbaabbbaaaaabaababbabaaabbbbababbbabbbbaaa
abaabbababbababbaaaabbabaaaabbaaaaaabaaa
bbbaabaaaaabaaaabaababaaabbaabaabbbbabaa
babbabbbbabababbaabaabbbbbbabbbbabbbbbab
abbbabaaaaaabaabaaabbabbabaaaabbabaaabbb
abaaabbababaaabaaababbaabbabaaabbabaabbbaaaabaaaaababbba
bababbbbbaabaaaabaabababbbbaaabaaabbbbaaaabbbbba
ababbbbbaabababbaaababaababbbbbaabaabbaaabaaaaabaabbbbba
babaabaaabbababbaaabbbabbaababba
baaaabbbbbaaaaaaaababbbbaabaabba
abbababbaabbbbbbbbbbbaba
baaaabaaaabbbaaaabababbbbaaabbabaaaabaaaababaaaabbabbbaa
baababbaaaaaaaaababbaabaabbaaabaabbbbaababbbabaabbabbaaabaaaabbbbaaababa
abaaabaaabbaabbbbababbaabaaababbaabababaabbbaaba
baabbaabbbbbababbbaaaaabaaaabaababbbaaababababaababbaabaababbaab
abbbaabbaaaabbaabbaabaab
aabbbaaaaabbbaaaabbaabab
aaaababbabaabbabaaaaabbb
aaababaaaaaaaabbaaaaabab
aaaaaaababbabbababababaa
aaabaaaabaaababbabaaabaabaaabaaabbabbbaaaaaaabaa
abbbababaabaabbbabaabababbaaababbaabbbaababbbaab
babaaaabbbbbbbbabbbaaaabbababaabbabbaaabbbbababbababbababaabbaaa
aaaabbabababbaaaaababbabbaabaaaaabbaabab
bbabaabbaaababaabbaabbbb
aabaabbbbbabbabaabbbbbbbaaaabaababbaaabaabbabbbb
babbabbbaaaabbaabaabbaabbbbbababbbaabbbaaaabbbbababbbaba
abbbbbbabbabaaaababbaabaabababbabbbbbababbbbbaababbbaaaa
ababbbbbaaaababbbabbabbbabaababbbbababbabbbaababaaabbbbb
baaaaaaabbaabbababababbabbbbbaba
bbaaabbbbabbaaaabbbbbaaabaabbaaa
abaaaaaaababbbabbbbbabba
babababbabbaaaaabbabbaabaabbbbaaabbaabba
bbabaaabbababaabbbbabbba
abaaabbaabbaabbbabbaaaaabaabbaabaabbaabb
babbaaabbabbbbbaaabaaaba
babababbbbbbbabbbababbba
abbbababbababaaabbbbababbabbbaba
bbaaaaabbaaababbbbbbaaabbabaabbbabbabbaa
bbabaaaaabaaaabbbaaaaaba
babaabaababbbbbaaaaaaabababababbaabaabaaabaabbbb
babbabaaaabbabbbbaabbbab
bbabaaabbbbbaaaaababababbaababaaabaabbbaabaaabbb
bababaaabbabbaabbabaaaaababbabbaabbabbba
abbaabababababbbabaaabbb
bbabbbaaaaaabbbbbbbaaababbabaabaaabaaabbaabaabaa
baabbaabbabbbbabbaaabaab
aaaaaaabbbbbababbbbbababbabaabbabbbbbbbb
baabaaaabaabbbbabbaaabbababbabaababaaabb
bbaaaaaaabaababbbbbaabaababbaaba
bbbababaaababbaababaaaabbbaabaabbaabbbbb
abaabbabababaaaabbbaabbabaababbbbabbabba
bbbabababbbbbaaabbbbaaabaabbbbba
abbaabbbbbbbababaaaabbbbabbababbbbaabbab
abaaabaabbabbbaaaabbabbbbbbaabab
babaaaaabbabaaaabbabbaaaababababaababbabbabaabba
bbaaabbbbabaaababbabbabaaaaaaababababababaaaaabbabbabbabbaabbbaaaaaaabba
abaaabaaaaabbaabababaaabbaababaababaabbabbbbbbababbbbaba
bbababbababaaababbabbbba
abbbabbaaababbaabbabbaaaaaabaaaababaabab
aaababaababaabaaaaababbbabaabaaa
bbbbbbaababbaaabbbbaaabaaaaaaaabbbbaaababaaabbab
babbbbbaaabababbababaaaababbbabbaabaabba
bbaaababbbabaababaaabbaabbabaaaaaaaabbaabaaaaabb
aabbbaabbbabaababaabbaabbaababba
bbaaababbabbbabbbabaabbbbbababbb
aaababbaaaaaaababbbaaabbabbbaaabaabbbbaaaabaabab
aaababaaabbbabababaaabbabbaaabaaaaabbbba
bbaaaaaaabbabaabbbbababaaaaabbbbaabaaabb
bbabbbababbbbbbbaaaabbaabbaabababaabaabb
babababbabaaabbabbbabbbb
bbabbaabababaaaaaabbabaabaabaabaaabbaaab
aaaaaaabbbabababbbaaaaba
baababaabbabbababaaaaaab
ababababababababbbbbbabbabaaabababbbbbaa
abaabaabaabaaaaaabbababaabbbabbb
babbbbabbababaabbaababba
bbabaaabbaababaaaaaaaaaa
baaabbbbbbbababaabaababaaabababbabbaababababaaba
abbababbbabaaaabaaaaabba
abaababbaabbbaaabbbabbbababbbbbaabababababbbbbabbbbabaab
bbabbbaabaaabaaaaaaaaabbbbaaaaabbbbbbaab
abbbbaababaabbababbbaaabbaabbbab
abbbabbaabbbababbbbaaababababbba
abbaabbbababaabbabaaaabaabaaaabbbabbaaba
aabbbbbabbaaaabbabbbbbababaabaabbabbabbbabbaaabbbaabababababbbbaaabbababbbabbbba
bbaaabbaabaababbababbaba
abaaabbaabaaabaaaaabbabbbabbbaab
ababababbbabaabbabaabaab
aababbabbababbbbaababaaa
abbaaabaaaabbaabbbbbbaab
aababbbbabbaabbaaabaaaaaabaababbabbbbbbbbabaabbbbbabbabb
ababaabbaaaabaabababbaaaabbbababbbabbbbb
abaabbabbababaaabbbabababaabbabbbbaaaaba
bbbaabbabbabbbabbabaaaaaaaaababbaaabbaabbababaaa
aabbabaaabbbabbabaababababaaaababaababaabaabbbaaabaabbaaabbabbba
aaaabbbbbaaababbbababaabbaaaabbbbbabababbaaaaabb
baaaabbbbbabaaaaaaababbb
abbbbaabaaabbbbbbababaaaabaabbbbbbaabaaabbbabbabbbbaaaabaabbbbabbababbbaaabbbabb
bbaaaabbabaaaabbabbaaababbbabaaabaaabbba
abbababbbbbaabbaaaaaabba
babbabaabbbbbabbaaabaaab
abaaabbaaaababaabbaabbbb
abaabbabaaabbaabbaabababbbbabaaaabababba
ababababbabbbaaaababbabb
bbbbabaabbbbbbbbbabbbabbbbbbabaa
babaaaaaaabbabbababaabaababbabba
bbaaabbabababaabaaaaabab
abbbaaabaabaabbbbabbaaababbababbbaabaaab
abaaabaaaaabbabbbbbaabaaababbbbbaabbbbba
aabababbaaaabbbaaaabbbba
aabbbaabbbbaaabbbbbaabbaabababaa
bababbabbbabaababbbaaababababbaaaababbaabbbababb
bbbababaaababbabbabbbaba
aababababababbaababbbaba
aababbabaabbabbbaabaaaabaabbbabb
bbabababbababaaaaaababbabbbaabbb
aababbabbbaaaaabbbabbbba
bbaaaaabbaabaababaaabaaaaababbabbbbbaabbbaabaabbaaaaabbb
baabbaabbbbaaabbababababbbaabbbb
aaaabaaaaaabaaababaababbabbbbbbbababababaaabbbbbaabaaaba
abbbababbababbaabababbba
abbbbbbbaababbabbabbbaaaabaaaabbbaaabbbbbbaaabaaaaaaabbababbbbaa
babbbbbababbaaaaaaaaabaa
abbbbbbaaaaabaabbaaaaabb
aabaaaabbabababbbbaaababaabbbaabbaabbaaabbaabbaabbbbabaa
baaaabbbbaaabbbbaabbbaabbaabaabaaaaabbaaaaaaabaa
aaababbabababaaaaababbbbabababba
bbabbababaabaabaaabbbbbbababaabbabaaaabbabbbbbab
aababbabbbbaaaabbbaababaaababbaabbbbbaba
bababbabbbbbbbaababbbbaa
ababababaaaaaabaabbbbbbaaababbaabaaabaaaaabaaabb
aabbabbbababaaababaababbaababaaa
bbbaabbabaabbbbabbbaabbabaaaaaaa
aabababbabbaaabaaaabaaaaaaabbbabaabbbaba
aaabbaabbbbabaababbaaaab
baabbbbaaaaabaabbaaaaaaa
aaabbaaaabbbabaaababababbbabbbaabbbbaaaaabbbbaaa
aabbbaabbbbbbabbabaababaaaabaabaabbaaaaa
babbabaaaabbbbbbaaabababbbbbbaab
bbbbbabbbababababaaabaaaabaabbbbabaaabab
babbbbbabbaaababbbbabbaa
aaaaaabbbabbbbabbbaaaaabbbbaaaabaabaabaabaababbb
aabbbaaabbbbaaaaabaabaaa
aabababbbababbabaaaaabba
bbbbababbbaaaaaababaabba
aabbaaaaaabbabaaaaaaaabbbbaaabbabbbbbbab
aaaaaabbbbbbababbaaabbba
bbaaaaaababbababbbaaabaa
aaabbaaabbabbbababbbbabbbabaaaaaabbabbababbbbabaabaabbba
babaabaaaaababaabaabbaba
bbabbabaaabbbbabaaaaaababbbbaaabaabaaaababbbbbab
bbababbaabaababbbabbabbbbbaabbba
baaabbaaababbaaabababbabaabbaaaabaaaaaaa
abaaabababbbaaaaaaaaaabbbababbbabababbab
aaaaababaaabbbbbabbbbbab
aaaabbbabbaaaaaaaabaabaa
aabbbbbbabbaaababbaaaaaaaabbabbbbaabaabb
aabbbaabaaabaaaaaabbbbaabaabbaaa
ababbaaaabbbababbbbababb
babaabbbbaababbbbabbaaaaababbabababaaaabaabaaabaabaabbbababbbabb
baaaabbabbbbabbbbababbbbbbabbbaabbbbaaaabbbabaaa
aaabaaaaaaabaababbbbbabbbaababbaaabbaaba
bbabbaaaababaaabbbababaaaaaaabaaaaaaababaaabbbba
aaaabaabaabababbabaabbbb
bbababbaaababbabbabababaaabbaaba
abaaaabbbabbabaabbbbbbab
babaaaababaababaaabbabbbbbbbabba
aaaabaabaaabbabaaaabaaaaaabbbbaaaaaaaabbbabaabbbababbbbb
aaababaababaaabaabbaabbbaaabaaaababaabbbbaabaabb
baababaabbbbbbbababbaaabababbaaaaaaabbaabbabaabbbaaaaabbaabbbbba
bbabbaaabbbaaaabababbbba
bbbbaabbbabaaaaaaaaaaababaabaaaabaabbbabbbaababbbabbbbbbaabaaabb
abaaaabaaaaabaabababaaaabbbbaaab
ababaabbbbbbababbabbbbababaaaaaaabbbaaaa
aaaabbbbabbbbbbaabbbbabbabaaabbb
aabaababbbbbabbabbaaabaaabbaaaab
bababbabbaaaabbbabbabbab
ababbbbbbbbaabaaababbbbbbbaababb
aababbaaaaaabbbbaabbaaaababababbaabaaaaababbbbbbaabbbabb
bbaaaabbabbbbbbaaaabbaabaabbabab
aabbabbaaabaaaabbaababababaaabbb
ababababbbaaaaabaaaabbbaabbbbbbabaabababbabaaababbaabbbabbaabbaa
aabbabbaabbababbabbabaabbabbabba
baaaabbbabbabaabaaabbaabbaaaabaabaaabbba
bbbbaaabbabaaabaababaaaababbababababbaaababaaabbaabbbabbababbbba
bbbabaabbbbaaabababbaaabababbbbaabbababa
bbbaabaaaabbbbbbababbbbbababbbabbbabbbbabbbabbaa
babbababaaaabbbbabbbbaaa
bbabbbabbbaaaaaaaabaaabb
bbabababbbabaaabbaabbbbaaababaaa
aabaaaabbbbaaaaabababbbbabbaabba
aabbbbbbbabaaaaabaaaabaa
bbaaaaaabbbbbabbbbaabbba
bababbbbbabaaabbaaaabbba
ababaaabbababaabababbbbbabbbaaabbbaabbba
bbbbbbbaaaabbbababaaaaab
aaababbababbababbabbbaaaaaababababaaaababababbabbabbabaabaababbabbaaababbbabbbab
babbababbbabaabaabbbaaaa
babbabaaaaaabbabaababbba
babbaaabbabaaaaaaaaabbbbbbbaabbaaababbba
aaabaababaabaaaaaaaabaabaababababbaabbba
bbbaabbabbbaaaaaaabbbaabbbaaaaababaaaaaaaaaabaaaaaabbbba
abbbabbabbababbababbaaba
bbbaaaaabababbaabbbabaaa
babbabbbabbaaabaabbbaabbaabbbbaaaaabbabbaaabaababaabbaaa
bababbbbbbabbaaaabababaa
bbabbaabababababbaaaabaa
babaabaabbabaabbabbbbbbbababaaaaaabbbbbbbbbbababbaabbaba
bbaaabbaaaabaaaaabbaababaabbabab
bbbaaaaaabbbabbaaababbba
aaaabbaaaabaabbbbabaaaabbbbbbbbb
abbababbbbabbaaabaabaaab
aaababbbabbbaaabbbaaabbbaababbbbbabababaaababababbaabaab
bbabbbbaababbbaaabbbbabaaababaaa
bbbaabaaabbbbabbbaaabaaaaabaaaabbbbbaababbaaabaaaaaaaaaa
aaabbbabbbaaababbbabbaaabaaabbaaaaabababbaabbbab
bbabaabbaabbbbaaaabbaaaabaababbbabaabaaa
baaabbbbbbaaabbaabbbbbbaaaabaaab
bbbaaabbabbaaaaabaababbb
aabbabbbaaabaabbbabababbbabbbbabbbabaaabaaaaaaaaaaabbbba
bbbaabbaaaaabbbababbbbaa
aaaaaaabbbaaababaaabaabababbbaba
babababbbaababababaaaabaaaabbbaa
bbbaaaaaabbbbaabaaabaabbbbbaaabb
bbbbbaaabbbbbbbaaaaabbaaaaaabaaa
aabababbaaabbbabbbabaabbbaaabababaaaaaaa
bababaaabbabbbaabaabbaabaaaabbbbbaaababbbbabbabbbaababbb
bbbbbabbaaabbaabbbaababb
bbaaaabbaaabbabbbbabbbaababbbaabbbbbbbab
ababaabbbbabbaabbaaaaaaa
abaaaabaabaababbbababbabaabaababaaaaaaaa
abbbabaabbabababbbbaaaaaabbaabab
bbbbbabbaabbbbaaabbbbbba
bbaaaabbaaaababbbbbbbabbbababbbbaabbabaaaaabbbbbbabaabba
bbbaabaababaaaabaaabbbba
bbababbabbbbabbababaababbbabbbbbaabaabbaabbbabab
abbbabbabbabaabbbaababaaababaabbbbaabaaa
bababaaaaabbbaabbbbbbaabbaabbabb
abbbbbbaabbaaaaaaabbaaaaaabbbaaababaababbbbabbba
bbbabababbbaaabbabbbaaababbbabbb
aaaabaabaabbaaaaaaaaaabababbaabb
bbaaabbbababaabbbbbbbaaaababbabaaabbbbba
bbbaaabbaabaabbbaabbbbaaaababbbbabbbaabbbbaabbba
ababaaabbbabbbabaabababbabababaabbababaa
aabbabbbbabbaaababbbbbab
abaaabbabababbababbaabbbaaaabbabaababbaabbababaaabababbabbbbbbbb
abaabaaababbaabbbbbabaabbabbaabbabaabbaa
ababbbbbaaababaaaababaaa
abaaaabbaabbabbaaabbaaba
baabaaaabbbbababaabbabaaaababbaaabbabbbaabaabbaa
aaabaababaaababbaabbabbbbbbaabbb
abbbababbbabababbaabaabababbabababbbabbaaaaaaaaabaabbabb
abaaabbaaaaaaabbaaaabbaaaaababbababbabaabbaabbabbaabaabb
bbbaabaabbaaaaabaaabbabbaaaababa
bababbaaabbabbabbaaabbabbabaaabbaaaaabba
aabaabbbbaabbbbabababaababaabbbbbbbabbba
bbaabbbaabaabaaabbaabbbb
bababababaaaabbbbbaabbab
bbbbbabbaabaabbbbababbaaabbbaababbbbbbbb
abababaabbbbaaaababaaaaabbaaabbbabbababbbabaabba
abbbbabbbaabbbbaaabbbaababbbabbabaaaabaaaababaab
abaaaaaabababbaaaabbaaab
bbaaaababbbbbbbbbaaaabab
bbaaabbbaababababaabaaaaabaaabaaababbbabaabaaaababbabbbabbbbabbbababbbbaabbabbab
bbbbaaabbbbabbaaaababaaabababaabbabaabababbbbabbbabbbabbabaabbabbbbaaaaa
aababbabababbbbabbaabbbbbbaabaaaaabbaaabbaaaababbabbabaaababaaaa
aabbbbbbbababbabbbaabaaaabaaaaaabbbbababaaabaabaaabbbbbbabaabbbbaaababbbbaaaabba
baabbbbaaababbbbbbbbaaababaaaaabaabaabab
abaaaababbbbbbbaaaaaaabbbababbaaabbaabab
bbbbaaaaabbbabaaaaaaaaaa
bbbabaabbababbbbaabbabab
bbabaaaaabbaaabaabbaabba
bbabaaabbaabaaaababababaaaabbbbbbbaababb
abbbbaaababaabaababaabbbaabbbbbbbabaabbb
aabbbaababaababbaaabababbababaabaabaaaaa
baaabbbbaabbabbaabbbabbb
aaabbabbbaaabbaaaabbaaaabaabaabb
abaaabbababbaaaaabbbaaaa
aabbabbaaaabbabbaaabbbba
baaabaaabbbbabaabbbabbbbabaaaaababaaabaaabbbbbbaababbbbbbbbbabbaabbabbaababbaabababbaaba
aaabbabbbbbbaaabaaababbbbabbbaaaaaabbbba
aaabaaaaaabbabaaabaabbabaababbbabaababbb
aabababbabaababababbbaba
bbbbaaaabbaaaaaababaabbb
baabaababaaaabbbabbbbaabbaabbabb
baaaabbbaaaaaabaabbbaabbbabaabaaabbaaaab
aaabaabaaaabbabbbbaabbbb
bbbaaaaaababaaaababaabaabbbaabaababbaaaabbaaaaaaaabaaabb
abaabababbbaabaabbaaaaabaabbabab
aaababaabababbaabbbbbaaabaaabbbbbabaababbaabbaba
aaaabaababaabbabaaabbaaaababaaabaaabaabababbababaababaab
aaaaaabbaaabbabbbaabbbab
bbabbaabbbabbaabbbabbaaabbbbbaba
baabbbbaaaaaaababbbbbbbaabaabbbaaabbaabb
bbaaababababaaabbabbbaba
baaabaaabbbaaababbabbbaaaabbabaaabbabbab
bbaaabbbaaabaabbbaabbabb
bbbabaabaabbbbbbbabaabab
babbaaaaaaababbabaabaaaaababaaabbaabaabababababaaaaaabaabbaabbba
bbabbaabbaaabaaabaabaabbaabbabab
babbaaabaaabaaaabaaabbbbaababaaababbbbaa
abbaaaaababbbbbaabbaabaa
babbabababaaaabbbbbabaaa
abaaabaabbaaabbaaaabaabbaabbbabaaaaababa
bbbbabbbabbaabbabaaabbbaabbababbbabbbaabaabbababaabbabaabbabbbaaabaaabbbbbbabbaa
aababbabbbabaababbabaaab
baabbbbabbaababaaabababbaaabbabbaaabaabbaaabbaaabbabbbbbabbbbaaa
ababababababaaaabbbbabba
aabbbaaaaaababbbbbbaabaaabbbabababbaabbbaaaaabaa
bababaabbabbaaabbbbbbaba
abaaaabbbababbbbabaaabaaabbaaaab
babbababbaabbaabaaababaabaaabbaaaabbaaabbbababbbbabbbbaa
aaaabbababbbaabbbababbbbaaababbbabbaabab
bbaaaaaababbbbbaaabbbbbbabbbaaababaabababaaaaaab
abaaabbaaababbabbbbbbaaaababaaaaaabbaaab
aaababbabbbaabaabababbaabbabbbababbaaaabbaaaaaabaaaaabbbbabbaabb
bababbaaababbaaababbabaaaababbba
baabaabaabaaabaaaabbbaabaaaabaaabaaabbab
aaaaaabbabbababbbbaabaab
baabaababbbbaaaababbabab
aaaaaabbaaaabbaaaaaaaababaaaabaabbababbb
bbabaaababaaaabaababbbbbabaabbba
aaaababbbabaaababbbbaaba
babbaaabbaabbaabbbbbababbabaabaaabbbbaabaabbaaba`
